-- MySQL Script generated by MySQL Workbench
-- Mon Jun  1 02:42:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema faculty
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `faculty` ;

-- -----------------------------------------------------
-- Schema faculty
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `faculty` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `faculty` ;

-- -----------------------------------------------------
-- Table `faculty`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faculty`.`Departments` ;

CREATE TABLE IF NOT EXISTS `faculty`.`Departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculty`.`Specialities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faculty`.`Specialities` ;

CREATE TABLE IF NOT EXISTS `faculty`.`Specialities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Number` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculty`.`Faculties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faculty`.`Faculties` ;

CREATE TABLE IF NOT EXISTS `faculty`.`Faculties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(10) NOT NULL,
   PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculty`.`Prepods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faculty`.`Prepods` ;

CREATE TABLE IF NOT EXISTS `faculty`.`Prepods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Surname` VARCHAR(30) NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `Patronymic` VARCHAR(30) NOT NULL,
  `idEducation` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pr_ed_idx` (`idEducation` ASC) VISIBLE,
  CONSTRAINT `fk_pr_ed`
    FOREIGN KEY (`idEducation`)
    REFERENCES `faculty`.`Education` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculty`.`Education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faculty`.`Education` ;

CREATE TABLE IF NOT EXISTS `faculty`.`Education` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idFaculty` INT NOT NULL,
  `idSpeciality` INT NOT NULL,
  `idDepartment` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ed_fac_idx` (`idFaculty` ASC) VISIBLE,
  INDEX `fk_ed_sp_idx` (`idSpeciality` ASC) VISIBLE,
  INDEX `fk_ed_dep_idx` (`idDepartment` ASC) VISIBLE,
  CONSTRAINT `fk_ed_fac`
    FOREIGN KEY (`idFaculty`)
    REFERENCES `faculty`.`Faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ed_sp`
    FOREIGN KEY (`idSpeciality`)
    REFERENCES `faculty`.`Specialities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ed_dep`
    FOREIGN KEY (`idDepartment`)
    REFERENCES `faculty`.`Departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculty`.`Groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faculty`.`Groups` ;

CREATE TABLE IF NOT EXISTS `faculty`.`Groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(20) NOT NULL,
  `idEducation` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  INDEX `fk_gr_ed_idx` (`idEducation` ASC) VISIBLE,
  CONSTRAINT `fk_gr_ed`
    FOREIGN KEY (`idEducation`)
    REFERENCES `faculty`.`Education` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculty`.`Curators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faculty`.`Curators` ;

CREATE TABLE IF NOT EXISTS `faculty`.`Curators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idGroup` INT NOT NULL,
  `idPrepod` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cur_prep_idx` (`idPrepod` ASC) VISIBLE,
  INDEX `fk_cur_group_idx` (`idGroup` ASC) VISIBLE,
  CONSTRAINT `fk_cur_prep`
    FOREIGN KEY (`idPrepod`)
    REFERENCES `faculty`.`Prepods` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cur_group`
    FOREIGN KEY (`idGroup`)
    REFERENCES `faculty`.`Groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculty`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faculty`.`Students` ;

CREATE TABLE IF NOT EXISTS `faculty`.`Students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Surname` VARCHAR(30) NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `idGroup` INT NOT NULL,
  `zalikovka` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `№zalikovky_UNIQUE` (`zalikovka` ASC) VISIBLE,
  INDEX `fk_stud_gr_idx` (`idGroup` ASC) VISIBLE,
  CONSTRAINT `fk_stud_gr`
    FOREIGN KEY (`idGroup`)
    REFERENCES `faculty`.`Groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
